---

- name: 'Install apt-transport-https, software-properties-common, gnupg and wget on Debian'
  ansible.builtin.package:
    name:
      - 'apt-transport-https'
      - 'software-properties-common'
      - 'wget'
      - 'gnupg'
    state: 'present'
    update_cache: true

- name: 'Create /etc/apt/keyrings/ on Debian'
  ansible.builtin.file:
    path: '/etc/apt/keyrings/'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'Add the Grafana APT repository key on Debian'
  ansible.builtin.get_url:
    url: 'https://apt.grafana.com/gpg.key'
    dest: '/etc/apt/keyrings/grafana.asc'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: 'Add the Grafana APT repository on Debian'
  ansible.builtin.apt_repository:
    repo: 'deb [signed-by=/etc/apt/keyrings/grafana.asc] https://apt.grafana.com stable main'
    # repo: 'deb https://apt.grafana.com stable main'
    filename: 'grafana-stable'
    state: 'present'
