---
# grafana_server/tasks/main.yml

- name: 'Fail if prerequisites for TLS are missing: tls_certificate_crt_path'
  ansible.builtin.fail:
    msg: 'Variable tls_certificate_crt_path is not set'
  when:
    - 'enable_tls | bool'
    - 'tls_certificate_crt_path is undefined'

- name: 'Fail if prerequisites for TLS are missing: tls_certificate_key_path'
  ansible.builtin.fail:
    msg: 'Variable tls_certificate_key_path is not set'
  when:
    - 'enable_tls | bool'
    - 'tls_certificate_key_path is undefined'

- name: 'Populate the package name variable depending on the OS'
  ansible.builtin.include_tasks: package_name.yml

- name: 'Install the package'
  ansible.builtin.package:
    name: "{{ grafana_package_name }}"
    state: 'present'

- name: 'Create the grafana.ini configuration file'
  ansible.builtin.template:
    src: 'grafana.ini.j2'
    dest: '/etc/grafana/grafana.ini'
    owner: 'root'
    group: "{{ grafana_system_group }}"
    mode: '0640'
  when:
    - 'write_grafana_ini | bool'
  notify:
    - 'Restart the grafana service'

- name: 'Create the ldap.toml configuration file'
  ansible.builtin.template:
    src: 'ldap.toml.j2'
    dest: '/etc/grafana/ldap.toml'
    owner: 'root'
    group: "{{ grafana_system_group }}"
    mode: '0640'
  when:
    - 'write_ldap_toml | bool'
  notify:
    - 'Restart the grafana service'

- name: 'Start and enable the service'
  ansible.builtin.service:
    name: "{{ systemd_unit_name }}"
    state: 'started'
    enabled: 'true'
