---
# grafana_server/tasks/package_name.yml

- name: 'Set package name on openSUSE/SUSE'
  ansible.builtin.set_fact:
    grafana_package_name: 'grafana'
  when:
    - 'ansible_os_family == "Suse"'

- name: 'Set package name on openSUSE MicroOS'
  ansible.builtin.set_fact:
    grafana_package_name: 'grafana'
  when:
    - 'ansible_os_family == "openSUSE MicroOS"'
